# Generated by Django 2.2 on 2022-03-19 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='blog',
            table='bloglist',
        ),
    ]
