# Generated by Django 2.2 on 2022-03-19 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20220320_0409'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='blog',
            table=None,
        ),
    ]
